[pytest]
asyncio_mode = auto
testpaths =
    kuksa-syncer/tests
python_files = test_*.py
norecursedirs =
    .* 
    build
    dist
    bin
    cpp-tests
    vehicle-model-generator
    kuksa-syncer/manual_scripts
