#ifndef MATLAB_TYPES_H
#define MATLAB_TYPES_H

// MATLAB-compatible data types
// These mirror the types generated by MATLAB Coder

#include <stdint.h>
#include <atomic>

// Basic MATLAB types
typedef double real_T;
typedef float real32_T;
typedef int32_t int32_T;
typedef uint32_t uint32_T;
typedef int8_t int8_T;
typedef uint8_t uint8_T;
typedef bool boolean_T;

// MATLAB structure equivalents
struct VehicleParams {
    real_T mass;                    // kg
    real_T wheel_radius;            // m
    real_T frontal_area;            // m^2
    real_T drag_coefficient;        // Cd
    real_T rolling_resistance;      // coefficient
    real_T air_density;            // kg/m^3
    real_T gravity;                // m/s^2
    real_T max_engine_torque;      // Nm
    real_T gear_ratio;             // dimensionless
    real_T max_brake_force;        // N
};

struct PIDParams {
    real_T kp;     // Proportional gain
    real_T ki;     // Integral gain  
    real_T kd;     // Derivative gain
    real_T dt;     // Sample time
    real_T min_output; // Output saturation min
    real_T max_output; // Output saturation max
};

struct VehicleStates {
    real_T position;        // m
    real_T velocity;        // m/s
    real_T acceleration;    // m/s^2
    real_T engine_rpm;      // RPM
    real_T wheel_speed;     // rad/s
    real_T fuel_consumed;   // L
};

struct ControlInputs {
    real_T throttle_cmd;    // 0-100%
    real_T brake_cmd;       // 0-100%
    real_T target_speed;    // m/s
    real_T enable_pid;      // boolean
    real_T enable_abs;      // boolean
};

struct SystemOutputs {
    real_T vehicle_speed;       // m/s
    real_T distance_traveled;   // m
    real_T fuel_consumption;    // L/100km
    real_T pid_error;           // m/s
    real_T engine_power;        // kW
    real_T brake_pressure;      // bar
};

// MATLAB simulation parameters (like Simulink Configuration)
struct SimParams {
    real_T sample_time;         // Simulation timestep (s)
    real_T stop_time;           // Simulation duration (s)
    int32_T log_decimation;     // Data logging rate divisor
    boolean_T enable_logging;    // Enable/disable data logging
};

#endif // MATLAB_TYPES_H