export declare const REGEX: {
    EVERYTHING_BETWEEN_MULTILINE: RegExp;
    GET_EVERY_PLUGINS_USAGE: RegExp;
    FIND_BEGIN_OF_ON_START_METHOD: RegExp;
    FIND_VEHICLE_INIT: RegExp;
    FIND_VEHICLE_OCCURENCE: RegExp;
    FIND_UNWANTED_VEHICLE_CHANGE: RegExp;
    FIND_PRINTF_STATEMENTS: RegExp;
    FIND_PRINT_STATEMENTS: RegExp;
    FIND_EVERY_LINE_START: RegExp;
    FIND_LINE_BEGINNING_WITH_WHITESPACES: RegExp;
    FIND_SAMPLE_APP: RegExp;
    FIND_SUBSCRIBE_METHOD_CALL: RegExp;
};
